on:
  push:
    branches:
      - main
name: Build & Deploy to ACI
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login to Azure'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build & Push'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_ENDPOINT }}
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
        - run: |
            docker build . -t ${{ vars.DKR_IMG_NAME }}:${{ github.sha }}
            docker tag ${{ vars.DKR_IMG_NAME }}:${{ github.sha }} ${{ secrets.ACR_ENDPOINT }}/${{ vars.DKR_IMG_NAME }}:${{ github.sha }}
            docker push ${{ secrets.ACR_ENDPOINT }}/${{ vars.DKR_IMG_NAME }}:${{ github.sha }}
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.AZ_RESOURCE_GROUP }}
            dns-name-label: ${{ serets.AZ_DNS_NAME_LABEL }}
            image: ${{ secrets.ACR_ENDPOINT }}/${{ vars.DKR_IMG_NAME }}:${{ github.sha }}
            cpu: 1
            memory: 1
            registry-username: ${{ secrets.AZURE_USERNAME }}
            registry-password: ${{ secrets.AZURE_PASSWORD }}
            name: mtgvault
            location: 'central us'
